logging:
  level:
    com.bot.rsshubqq: debug
translate:
  appId: "20200322000402814"          #翻译app应用id
  securityKey: "vUckpxROgnk7m8d5ZUv9" #翻译app对应的密钥
  url: "https://fanyi-api.baidu.com/api/trans/vip/translate"  #翻译接口url
  targetLanguage: "zh"  #翻译目标语言
rsshub:
  downloadFailNotify: true #是否在图片下载失败时通知
  downloadFailNotifier: 451060876 #图片下载失败通知
  enable: true    #是否启动rss的抓取
  query-time: 300 #查询间隔时间(s
  item-pause-time: 5 #每个RssItem查询间隔时间(s
  dbPath: db/dbFile.json #数据目录
  tempPath: tmp/  #临时文件存储
  urlTempAccess: false #是否开启临时文件访问
  localUrl: localhost #外部访问域名
  accessPort: 8081    #外部访问端口
  proxyUrl: 192.168.199.8 #代理地址
  proxyPort: 10809 #Http代理端口
  errorInfo: false #是否开启RssHub错误提示
  errorInfoCount: 0 #RssHub错误提示阈值; 为0则默认为列表数量
  rssList:
    - name: "test"
      url: "https://rss.shab.fun/twitter/user/VOIDInteractive/exclude_replies"
      groups:
        - 1059769975 #测试群
      translate: false
      proxy: true