logging:
  level:
    com.bot.rsshubqq: debug
translate:
  appId: "20200322000402814"          #翻译app应用id
  securityKey: "vUckpxROgnk7m8d5ZUv9" #翻译app对应的密钥
  url: "https://fanyi-api.baidu.com/api/trans/vip/translate"  #翻译接口url
  targetLanguage: "zh"  #翻译目标语言
rsshub:
  downloadFailNotify: true #是否在图片下载失败时通知
  downloadFailNotifier: 451060876 #图片下载失败通知
  enable: true    #是否启动rss的抓取
  query-time: 300 #查询间隔时间(s
  item-pause-time: 5 #每个RssItem查询间隔时间(s
  dbPath: db/dbFile.json #数据目录
  tempPath: tmp/  #临时文件存储
  urlTempAccess: false #是否开启临时文件访问
  localUrl: localhost #外部访问域名
  accessPort: 8081    #外部访问端口
  proxyUrl: 192.168.199.8 #代理地址
  proxyPort: 10809 #Http代理端口
  rssList:
    - name: "Twitter-RoN"
      url: "https://rss.shab.fun/twitter/user/VOIDInteractive/exclude_replies"
      groups:
        - 415103457  #RON手残挂靠中心
        - 1059769975 #测试群
      translate: true
      proxy: true
    - name: "Twitter-R6"
      url: "https://rss.shab.fun/twitter/user/Rainbow6Game/exclude_replies"
      groups:
        - 1079372331  #龙裔宝宝后宫群
        - 930678842   #浙理工电竞社彩虹六号群
        - 1059769975  #测试群
        - 108471629   #今天你们可爱了吗
        - 788309241   #Re9总群
      translate: true
      proxy: true
    - name: "Twitter-GB"
      url: "https://rss.shab.fun/twitter/user/GroundBranch/exclude_replies"
      groups:
        - 1059769975  #测试群
      translate: true
      proxy: true
    - name: "Twitter-Test"
      url: "https://rss.shab.fun/twitter/user/BoneD_Exp/exclude_replies"
      groups:
        - 1059769975  #测试群
      translate: true
      proxy: true
    - name: "Twitter-NWI"
      url: "https://rss.shab.fun/twitter/user/nwinteractive/exclude_replies"
      groups:
        - 491952216   #NWI游戏交流群
        - 750013632   #InsSS CNT 闯泥潭 1群
        - 1059769975  #测试群
      translate: true
      proxy: true
    - name: "Twitter-SandStorm"
      url: "https://rss.shab.fun/twitter/user/InsurgencyGame/exclude_replies"
      groups:
        - 491952216   #NWI游戏交流群
        - 750013632   #InsSS CNT 闯泥潭 1群
        - 1059769975  #测试群
      translate: true
      proxy: true
    - name: "Twitter-ISMC"
      url: "https://rss.shab.fun/twitter/user/ISMCmod/exclude_replies"
      groups:
        - 491952216   #NWI游戏交流群
        - 750013632   #InsSS CNT 闯泥潭 1群
        - 1059769975  #测试群
      translate: true
      proxy: true
    - name: "Bilibili-Longyi"
      url: "https://rss.shab.fun/bilibili/user/dynamic/1932102"
      groups:
        - 1079372331  #龙裔宝宝后宫群
        - 1059769975  #测试群
      translate: false
      proxy: false
    - name: "Bilibili-Hum"
      url: "https://rss.shab.fun/bilibili/user/dynamic/26483671"
      groups:
        - 108471629   #今天你们可爱了吗
        - 1059769975  #测试群
      translate: false
      proxy: false
    - name: "Bilibili-Hum2"
      url: "https://rss.shab.fun/bilibili/user/dynamic/1049200059"
      groups:
        - 108471629   #今天你们可爱了吗
        - 1059769975  #测试群
      translate: false
      proxy: false
    - name: "RoN-SteamNews"
      url: "https://store.steampowered.com/feeds/news/app/1144200/?cc=CN&l=schinese&snr=1_2108_9__2107"
      groups:
        - 415103457  #RON手残挂靠中心
        - 1059769975 #测试群
      translate: false
      proxy: false