spring:
  profiles:
    include:
      - rsshubqq
      - steamBranch
  cq:
    plugin-list: #插件列表
      - com.bot.main.plugin.FilterPlugin
      - com.bot.rsshubqq.plugin.RssHubPlugin
      - com.bot.steamBranch.plugin.SteamBranchPlugin
      - com.bot.main.plugin.BaseRespondPlugin
bot:
  replyGroup: false   #响应群消息
  replyPrivate: true  #响应私信消息
  earlyWarningGroupEnable: true     #告警信息是否发送给群聊
  earlyWarningPrivateEnable: false  #告警信息是否发送给私聊
  earlyWarningGroupList: #告警信息发送群聊列表
    - 1059769975
  earlyWarningPrivateList:  #告警信息发送私聊列表
  admins:
    - 451060876
ping-config:
  messageCount: 3   #消息记录时间数
  messageGap: 1000  #消息间隔（ms
server:
  port: 8081
logging:
  config: classpath:logback-spring.xml
  level:
    root: info
    com.bot.main: info
rest-template-config:
  connectionTimeout: 5 #设置网络连接超时（s
  readTimeout: 60      #设置读取超时（s